import { allocateLead } from "@/lib/allocator";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";

const LEADS_PER_BATCH = 10;
const TARGET_SERVICE_CODE = "SERVICE_1";

export async function POST(): Promise<Response> {
  if (process.env.NODE_ENV === "production") {
    return new Response("Not found.", { status: 404 });
  }

  try {
    const service = await prisma.service.findUnique({
      where: { code: TARGET_SERVICE_CODE },
      select: { id: true, name: true },
    });

    if (!service) {
      return jsonResponse({ message: "Target test service is not configured." }, 500);
    }

    const batchSeed = process.hrtime.bigint().toString();
    const allocations = await Promise.allSettled(
      Array.from({ length: LEADS_PER_BATCH }, (_, index) => {
        const phone = `${batchSeed}${index}`;

        return allocateLead({
          phone,
          serviceId: service.id,
          source: "test-api",
          rawPayload: {
            name: `Concurrency Test Lead ${index + 1}`,
            phone,
            city: "Test City",
            serviceType: service.name,
            description: "Generated by concurrency test endpoint.",
          },
        });
      }),
    );

    const details = allocations.map((result, index) => {
      if (result.status === "fulfilled") {
        return {
          index,
          status: "success" as const,
          leadId: result.value.lead.id,
          phone: result.value.lead.phone,
          providerIds: result.value.assignments.map((assignment) => assignment.providerId),
        };
      }

      return {
        index,
        status: "failure" as const,
        error: result.reason instanceof Error ? result.reason.message : "Unknown allocation error.",
      };
    });

    return jsonResponse(
      {
        service: service.name,
        successes: details.filter((detail) => detail.status === "success").length,
        failures: details.filter((detail) => detail.status === "failure").length,
        details,
      },
      200,
    );
  } catch (error) {
    console.error("Failed to generate test leads", error);
    return jsonResponse({ message: "Internal server error." }, 500);
  }
}

function jsonResponse<T>(body: T, status: number): Response {
  return Response.json(body, {
    status,
    headers: {
      "Cache-Control": "no-store",
    },
  });
}
